# Generated by Django 4.1.7 on 2023-03-31 11:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Hall",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("hall_number", models.IntegerField()),
                ("sits_layout", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Movie",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100, verbose_name="Movie Name")),
                ("length_mins", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="MovieSession",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("starting_time", models.DateTimeField()),
                (
                    "hall_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="cinema_backend.hall",
                    ),
                ),
                (
                    "movie_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="cinema_backend.movie",
                    ),
                ),
            ],
        ),
    ]
