# Generated by Django 4.1.7 on 2023-04-06 21:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Genre",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100, verbose_name="Genre Name")),
            ],
        ),
        migrations.CreateModel(
            name="Hall",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("hall_number", models.IntegerField()),
                ("sits_layout", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Movie",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100, verbose_name="Movie Name")),
                ("length_mins", models.IntegerField()),
                ("grade", models.FloatField()),
                ("description", models.TextField()),
                (
                    "directed_by",
                    models.CharField(max_length=100, verbose_name="Producer"),
                ),
                ("production_year", models.IntegerField()),
                (
                    "production_country",
                    models.CharField(max_length=100, verbose_name="Country"),
                ),
                (
                    "poster",
                    models.ImageField(
                        height_field=3456, upload_to="posters", width_field=2304
                    ),
                ),
                (
                    "trailer_link",
                    models.CharField(max_length=255, verbose_name="Trailer Link"),
                ),
                ("genres", models.ManyToManyField(to="cinema_backend.genre")),
            ],
        ),
        migrations.CreateModel(
            name="MovieSession",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("starting_time", models.DateTimeField()),
                (
                    "hall_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="cinema_backend.hall",
                    ),
                ),
                (
                    "movie_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="cinema_backend.movie",
                    ),
                ),
            ],
        ),
    ]
