# Generated by Django 4.1.7 on 2023-04-06 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cinema_backend", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="movie",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="movie",
            name="poster",
            field=models.ImageField(upload_to="posters"),
        ),
    ]
