# Generated by Django 4.1.7 on 2023-05-04 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cinema_backend", "0002_movie_is_active_alter_movie_poster"),
    ]

    operations = [
        migrations.AddField(
            model_name="moviesession",
            name="ticket_price",
            field=models.DecimalField(decimal_places=2, default=75.0, max_digits=10),
            preserve_default=False,
        ),
    ]
