# Generated by Django 4.1.7 on 2023-06-04 17:49

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("cinema_backend", "0005_remove_movie_grade"),
    ]

    operations = [
        migrations.RenameModel(old_name="Reviews", new_name="Review",),
    ]
